#! /bin/sh
### BEGIN INIT INFO
# Provides:          Discord BOTs 
# Required-Start:    
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: Provides my custom bots for discord service.
### END INIT INFO

PYTHON_PROG=`which python3`

case "$1" in
  start)
	echo "Starting Discord Bots"
	${PYTHON_PROG} /root/.Discord_Bots/TOK_Bot.py &
	${PYTHON_PROG} /root/.Discord_Bots/SMART_Bot.py &
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  status)
	TOKBOT_PID=`ps ax | grep 'TOK_Bot.py' | grep -v grep | awk '{print $1}'`
	SMARTBOT_PID=`ps ax | grep 'SMART_Bot.py' | grep -v grep | awk '{print $1}'`
	if [ ! -z "$TOKBOT_PID" ] & [ ! -z "$SMARTBOT_PID" ] ; then
		echo "Discord BOTs are running with pid ${TOKBOT_PID} ${SMARTBOT_PID}"
	else
		echo "Discord BOTs are not running"
	fi
	;;
  stop)
        TOKBOT_PID=`ps ax | grep 'TOK_Bot.py' | grep -v grep | awk '{print $1}'`
        SMARTBOT_PID=`ps ax | grep 'SMART_Bot.py' | grep -v grep | awk '{print $1}'`
        if [ ! -z "$TOKBOT_PID" ] & [ ! -z "$SMARTBOT_PID" ] ; then
		echo "Stopping Discord BOTs"
		kill -9 ${TOKBOT_PID}
		kill -9 ${SMARTBOT_PID}
        else
                echo "Discord BOTs are not running"
        fi
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
